name: 🚀 Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Tự động deploy khi push vào branch main
  workflow_dispatch: # Cho phép deploy thủ công từ tab Actions

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-deploy"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: 📦 Upload static files
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Đường dẫn tới thư mục chứa file index.html

      - name: 🚀 Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
